profiles:
  - name: "llama-shim-gemma-4-26B"
    chat_model: "gemma-4-26B-A4B-it"
    responses_model: "gemma-4-26B-A4B-it"
    extra: {}
    tests:
      chat.tool_call:
        max_tokens: 128
      chat.tool_call.required:
        max_tokens: 128

  - name: "llama-shim-gemma-4-31B"
    chat_model: "gemma-4-31B-it"
    responses_model: "gemma-4-31B-it"
    extra: {}
    tests:
      chat.tool_call:
        max_tokens: 128
      chat.tool_call.required:
        max_tokens: 128

  - name: "llama-shim-qwen-3.6-35B"
    chat_model: "Qwen3.6-35B-A3B"
    responses_model: "Qwen3.6-35B-A3B"
    extra: {}
    tests:
      chat.tool_call:
        max_tokens: 128
      chat.tool_call.required:
        max_tokens: 128

